name: Release Package to GitHub Packages

on:
  push:
    branches:
      - main # Only trigger release workflow on main branch

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Check test coverage (80%)
        run: |
          echo "Checking coverage..."
          if ! npm run test:coverage | grep -q "All files.*[8-9][0-9]\.[0-9].*|.*100\.0.*"; then
            echo "Test coverage is below 80% threshold"
            exit 1
          fi

      - name: Build project
        run: npm run build

  publish:
    name: Publish to GitHub Packages
    needs: test-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (Latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yatongzhao0622' # Updated GitHub username

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release 